#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bash -n "$ROOT/install.sh" "$ROOT/update.sh" "$ROOT/reset-install.sh" "$ROOT/healthcheck.sh" "$ROOT/setup-channel-scanner.sh"
shellcheck -x "$ROOT/install.sh" "$ROOT/update.sh" "$ROOT/reset-install.sh" "$ROOT/healthcheck.sh" "$ROOT/setup-channel-scanner.sh"
test ! -e "$ROOT/config.php"
test -e "$ROOT/config.example.php"
test -e "$ROOT/worker.php"
! find "$ROOT" -maxdepth 1 -type f -name '*.zip' | grep -q .
! grep -RIE 'wireguard|v2ray|xray|3x-ui|wizwiz|mirzabot|vpn proxy' "$ROOT" --exclude-dir=.git --exclude='*.md' --exclude='installer_test.sh'
grep -q 'php8.3-fpm' "$ROOT/install.sh"
grep -q 'freebot-download@' "$ROOT/install.sh"
grep -q 'freebot-upload@' "$ROOT/install.sh"
grep -q 'certbot --nginx' "$ROOT/install.sh"
grep -q 'Telethon' "$ROOT/install.sh"
grep -q 'hachoir' "$ROOT/install.sh"
grep -q 'hachoir' "$ROOT/update.sh"
grep -q 'hachoir' "$ROOT/setup-channel-scanner.sh"
grep -q 'ffprobe' "$ROOT/healthcheck.sh"
grep -q 'FREEBOT_DOWNLOAD_WORKERS:-4' "$ROOT/install.sh"
grep -q 'FREEBOT_UPLOAD_WORKERS:-4' "$ROOT/install.sh"
grep -q -- '--parallel-session' "$ROOT/scripts/channel_history_scan.py"
grep -q 'ffprobe_video_metadata' "$ROOT/scripts/channel_history_scan.py"
grep -q 'channel_history_scan.py' "$ROOT/setup-channel-scanner.sh"
grep -q 'channel_scanner_send_code' "$ROOT/admin.php"
grep -q -- '--web-action' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--list-videos' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--download-message' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--upload-file' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--destination' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--min-message-id' "$ROOT/scripts/channel_history_scan.py"
grep -q 'InputMessagesFilterVideo' "$ROOT/scripts/channel_history_scan.py"
grep -q 'video_count_total' "$ROOT/scripts/channel_history_scan.py"
grep -q -- '--result-file' "$ROOT/scripts/channel_history_scan.py"
grep -Fq "functionEnabled('exec')" "$ROOT/media.php"
grep -Fq "'/usr/bin/timeout'" "$ROOT/media.php"
grep -q -- '--transport-probe' "$ROOT/scripts/channel_history_scan.py"
test -e "$ROOT/tests/telethon_exec_transport_test.php"
grep -q 'media_channel_import' "$ROOT/admin.php"
grep -q 'media_channel_batch_update' "$ROOT/admin.php"
grep -q 'split_destinations' "$ROOT/admin.php"
grep -q 'destinationForPosition' "$ROOT/media.php"
grep -q 'updateTelegramChannelBatch' "$ROOT/media.php"
grep -q 'claimChannelScan' "$ROOT/media.php"
grep -q "scan_status='scanning'" "$ROOT/media.php"
grep -q 'proc_open($command' "$ROOT/media.php"
grep -q 'uploadWithTelethon' "$ROOT/media.php"
grep -q "min(1024" "$ROOT/media.php"
grep -q "pipelineDepth=max(4" "$ROOT/media.php"
grep -q "WHEN 'downloading' THEN 0" "$ROOT/media.php"
! grep -q "active_tg.engine='telegram-mtproto'" "$ROOT/media.php"
grep -q 'source_last_message_id=GREATEST' "$ROOT/media.php"
grep -q 'source_video_count' "$ROOT/media.php"
grep -q 'media_scan_lease_seconds' "$ROOT/media.php"
grep -q 'SHOW FULL COLUMNS FROM media_jobs' "$ROOT/app.php"
grep -q "General error: 1364" "$ROOT/app.php"
grep -q 'cryptg' "$ROOT/install.sh"
grep -q 'cryptg' "$ROOT/update.sh"
grep -q 'idx_media_target' "$ROOT/install.php"
! grep -q "setSetting('channel_scanner_.*password" "$ROOT/media.php"
python3 "$ROOT/scripts/channel_history_scan.py" --self-test
php "$ROOT/tests/telethon_exec_transport_test.php"
echo "Installer test passed."
